
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Tabla49Campos", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://207.248.171.164:8085/Tabla49Campos.asmx?WSDL")
public class Tabla49Campos
    extends Service
{

    private final static URL TABLA49CAMPOS_WSDL_LOCATION;
    private final static WebServiceException TABLA49CAMPOS_EXCEPTION;
    private final static QName TABLA49CAMPOS_QNAME = new QName("http://tempuri.org/", "Tabla49Campos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://207.248.171.164:8085/Tabla49Campos.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TABLA49CAMPOS_WSDL_LOCATION = url;
        TABLA49CAMPOS_EXCEPTION = e;
    }

    public Tabla49Campos() {
        super(__getWsdlLocation(), TABLA49CAMPOS_QNAME);
    }

    public Tabla49Campos(WebServiceFeature... features) {
        super(__getWsdlLocation(), TABLA49CAMPOS_QNAME);
    }

    public Tabla49Campos(URL wsdlLocation) {
        super(wsdlLocation, TABLA49CAMPOS_QNAME);
    }

    public Tabla49Campos(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TABLA49CAMPOS_QNAME);
    }

    public Tabla49Campos(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Tabla49Campos(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns Tabla49CamposSoap
     */
    @WebEndpoint(name = "Tabla49CamposSoap")
    public Tabla49CamposSoap getTabla49CamposSoap() {
        return super.getPort(new QName("http://tempuri.org/", "Tabla49CamposSoap"), Tabla49CamposSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Tabla49CamposSoap
     */
    @WebEndpoint(name = "Tabla49CamposSoap")
    public Tabla49CamposSoap getTabla49CamposSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "Tabla49CamposSoap"), Tabla49CamposSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns Tabla49CamposSoap
     */
    @WebEndpoint(name = "Tabla49CamposSoap12")
    public Tabla49CamposSoap getTabla49CamposSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "Tabla49CamposSoap12"), Tabla49CamposSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Tabla49CamposSoap
     */
    @WebEndpoint(name = "Tabla49CamposSoap12")
    public Tabla49CamposSoap getTabla49CamposSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "Tabla49CamposSoap12"), Tabla49CamposSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TABLA49CAMPOS_EXCEPTION!= null) {
            throw TABLA49CAMPOS_EXCEPTION;
        }
        return TABLA49CAMPOS_WSDL_LOCATION;
    }

}
