
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Tabla49CamposSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Tabla49CamposSoap {


    /**
     * 
     * @param cveMes
     * @return
     *     returns org.tempuri.ArrayOfRespuesta
     */
    @WebMethod(action = "http://tempuri.org/getDatosPorClaveMes")
    @WebResult(name = "getDatosPorClaveMesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getDatosPorClaveMes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDatosPorClaveMes")
    @ResponseWrapper(localName = "getDatosPorClaveMesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDatosPorClaveMesResponse")
    public ArrayOfRespuesta getDatosPorClaveMes(
        @WebParam(name = "cve_mes", targetNamespace = "http://tempuri.org/")
        String cveMes);

    /**
     * 
     * @param nombre
     * @return
     *     returns org.tempuri.ArrayOfRespuesta
     */
    @WebMethod(action = "http://tempuri.org/getDatosPorNombre")
    @WebResult(name = "getDatosPorNombreResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getDatosPorNombre", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDatosPorNombre")
    @ResponseWrapper(localName = "getDatosPorNombreResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDatosPorNombreResponse")
    public ArrayOfRespuesta getDatosPorNombre(
        @WebParam(name = "nombre", targetNamespace = "http://tempuri.org/")
        String nombre);

    /**
     * 
     * @param curp
     * @return
     *     returns org.tempuri.ArrayOfRespuesta
     */
    @WebMethod(action = "http://tempuri.org/getDatosPorCURP")
    @WebResult(name = "getDatosPorCURPResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getDatosPorCURP", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDatosPorCURP")
    @ResponseWrapper(localName = "getDatosPorCURPResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDatosPorCURPResponse")
    public ArrayOfRespuesta getDatosPorCURP(
        @WebParam(name = "curp", targetNamespace = "http://tempuri.org/")
        String curp);

    /**
     * 
     * @param rfc
     * @return
     *     returns org.tempuri.ArrayOfRespuesta
     */
    @WebMethod(action = "http://tempuri.org/getDatosPorRFC")
    @WebResult(name = "getDatosPorRFCResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getDatosPorRFC", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDatosPorRFC")
    @ResponseWrapper(localName = "getDatosPorRFCResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDatosPorRFCResponse")
    public ArrayOfRespuesta getDatosPorRFC(
        @WebParam(name = "rfc", targetNamespace = "http://tempuri.org/")
        String rfc);

    /**
     * 
     * @param numeroCredito
     * @return
     *     returns org.tempuri.ArrayOfRespuesta
     */
    @WebMethod(action = "http://tempuri.org/getDatosPorNumeroDeCredito")
    @WebResult(name = "getDatosPorNumeroDeCreditoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getDatosPorNumeroDeCredito", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDatosPorNumeroDeCredito")
    @ResponseWrapper(localName = "getDatosPorNumeroDeCreditoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDatosPorNumeroDeCreditoResponse")
    public ArrayOfRespuesta getDatosPorNumeroDeCredito(
        @WebParam(name = "numero_credito", targetNamespace = "http://tempuri.org/")
        String numeroCredito);

    /**
     * 
     * @param desarrollador
     * @return
     *     returns org.tempuri.ArrayOfRespuesta
     */
    @WebMethod(action = "http://tempuri.org/getDatosPorDesarrollador")
    @WebResult(name = "getDatosPorDesarrolladorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getDatosPorDesarrollador", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDatosPorDesarrollador")
    @ResponseWrapper(localName = "getDatosPorDesarrolladorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDatosPorDesarrolladorResponse")
    public ArrayOfRespuesta getDatosPorDesarrollador(
        @WebParam(name = "desarrollador", targetNamespace = "http://tempuri.org/")
        String desarrollador);

}
